// mail service

// import { storageService } from '../../../services/storage.service.js'
import { storageService } from '../../../services/async-storage.service.js'
import { utilService } from '../../../services/util.service.js'

const MAIL_KEY = 'mailList'
const mailList = localStorage.getItem(MAIL_KEY) || createMails()

const loggedInUser = {
  email: 'user@appsus.com',
  fullName: 'Mahatma Appsus',
}

export const mailService = {
  MAIL_KEY,
  mailList,
  loggedInUser,
  getDefaultFilter,
  save,
  // _setNextPrevMailId,
  get,
  getComposeFromSearchParams,
}
// localStorage.clear()
function createMails() {
  const mails = [
    {
      id: 'e101',
      subject: 'Miss you!',
      body: `Would love to catch up sometimes, They are enjoying their vacation in Hawaii. He is studying for his upcoming exams.
      She isn’t attending the party tonight.
      They‘re not participating in the competition.
      We aren’t going out for dinner this evening.
      He‘s not wearing a jacket despite the cold weather.`,
      isRead: false,
      isReceived: true,
      isFavorite: true,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'shana@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },

    {
      id: 'e102',
      subject: `I'm happy.`,
      body: 'His dog barks loudly.',
      isRead: true,
      isReceived: true,
      isFavorite: true,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'dani@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },

    {
      id: 'e103',
      subject: 'My school starts at 8:00.',
      body: 'We always eat dinner together.',
      isRead: false,
      isReceived: true,
      isFavorite: false,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'service@motel.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e104',
      subject: 'They take the bus to work.',
      body: `He doesn't like vegetables.`,
      isRead: false,
      isReceived: true,
      isFavorite: true,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'momo@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e105',
      subject: `I don’t want anything to drink.`,
      body: `Those kids don’t speak English.`,
      isRead: false,
      isReceived: true,
      isFavorite: true,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'mani@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e106',
      subject: 'They will not complete the assignment on time.',
      body: `We‘ll have dinner at a fancy restaurant tonight.`,
      isRead: true,
      isReceived: false,
      isFavorite: true,
      isSent: true,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'user@appsus.com',
      to: 'random@user.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e107',
      subject: 'They are enjoying their vacation in Hawaii.',
      body: 'Fla plo love to catch up sometimes',
      isRead: true,
      isReceived: true,
      isFavorite: false,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'user@appsus.com',
      to: 'rani@user.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e108',
      subject: 'Thank you!',
      body: 'Fla plo love to catch up sometimes',
      isRead: true,
      isReceived: false,
      isFavorite: false,
      isSent: true,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'user@appsus.com',
      to: 'momo@mimi.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e109',
      subject: 'They are enjoying their vacation in Hawaii.',
      body: 'Thank you.',
      isRead: true,
      isReceived: false,
      isFavorite: false,
      isSent: false,
      isDraft: true,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'daniel@walla.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e110',
      subject: `We aren’t going out for dinner this evening.`,
      body: 'Fla plo love to catch up sometimes',
      isRead: true,
      isReceived: false,
      isFavorite: false,
      isSent: true,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'dani@walla.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e111',
      subject: 'Thank you!',
      body: `We aren’t going out for dinner this evening.`,
      isRead: false,
      isReceived: true,
      isFavorite: false,
      isSent: false,
      isDraft: false,
      isTrash: true,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'dorhakim100@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e112',
      subject: 'Miss you!',
      body: `Would love to catch up sometimes, They are enjoying their vacation in Hawaii. He is studying for his upcoming exams.
      She isn’t attending the party tonight.
      They‘re not participating in the competition.
      We aren’t going out for dinner this evening.
      He‘s not wearing a jacket despite the cold weather.`,
      isRead: false,
      isReceived: true,
      isFavorite: true,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'shana@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },

    {
      id: 'e113',
      subject: `I'm happy.`,
      body: 'His dog barks loudly.',
      isRead: true,
      isReceived: true,
      isFavorite: true,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'dani@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },

    {
      id: 'e114',
      subject: 'My school starts at 8:00.',
      body: 'We always eat dinner together.',
      isRead: false,
      isReceived: true,
      isFavorite: false,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'service@motel.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e115',
      subject: 'They take the bus to work.',
      body: `He doesn't like vegetables.`,
      isRead: false,
      isReceived: true,
      isFavorite: true,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'momo@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e116',
      subject: `I don’t want anything to drink.`,
      body: `Those kids don’t speak English.`,
      isRead: false,
      isReceived: true,
      isFavorite: true,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'mani@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e117',
      subject: 'They will not complete the assignment on time.',
      body: `We‘ll have dinner at a fancy restaurant tonight.`,
      isRead: true,
      isReceived: false,
      isFavorite: true,
      isSent: true,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'user@appsus.com',
      to: 'random@user.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e118',
      subject: 'They are enjoying their vacation in Hawaii.',
      body: 'Fla plo love to catch up sometimes',
      isRead: true,
      isReceived: true,
      isFavorite: false,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'user@appsus.com',
      to: 'rani@user.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e119',
      subject: 'Thank you!',
      body: 'Fla plo love to catch up sometimes',
      isRead: true,
      isReceived: false,
      isFavorite: false,
      isSent: true,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'user@appsus.com',
      to: 'momo@mimi.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e120',
      subject: 'They are enjoying their vacation in Hawaii.',
      body: 'Thank you.',
      isRead: true,
      isReceived: false,
      isFavorite: false,
      isSent: false,
      isDraft: true,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'daniel@walla.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e121',
      subject: `We aren’t going out for dinner this evening.`,
      body: 'Fla plo love to catch up sometimes',
      isRead: true,
      isReceived: false,
      isFavorite: false,
      isSent: true,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'dani@walla.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e122',
      subject: 'Thank you!',
      body: `We aren’t going out for dinner this evening.`,
      isRead: false,
      isReceived: true,
      isFavorite: false,
      isSent: false,
      isDraft: false,
      isTrash: true,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'dorhakim100@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e123',
      subject: 'They take the bus to work.',
      body: `He doesn't like vegetables.`,
      isRead: false,
      isReceived: true,
      isFavorite: true,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'momo@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e124',
      subject: `I don’t want anything to drink.`,
      body: `Those kids don’t speak English.`,
      isRead: false,
      isReceived: true,
      isFavorite: true,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'mani@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e125',
      subject: 'They will not complete the assignment on time.',
      body: `We‘ll have dinner at a fancy restaurant tonight.`,
      isRead: true,
      isReceived: false,
      isFavorite: true,
      isSent: true,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'user@appsus.com',
      to: 'random@user.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e126',
      subject: 'They are enjoying their vacation in Hawaii.',
      body: 'Fla plo love to catch up sometimes',
      isRead: true,
      isReceived: true,
      isFavorite: false,
      isSent: false,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'user@appsus.com',
      to: 'rani@user.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e127',
      subject: 'Thank you!',
      body: 'Fla plo love to catch up sometimes',
      isRead: true,
      isReceived: false,
      isFavorite: false,
      isSent: true,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'user@appsus.com',
      to: 'momo@mimi.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e128',
      subject: 'They are enjoying their vacation in Hawaii.',
      body: 'Thank you.',
      isRead: true,
      isReceived: false,
      isFavorite: false,
      isSent: false,
      isDraft: true,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'daniel@walla.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e129',
      subject: `We aren’t going out for dinner this evening.`,
      body: 'Fla plo love to catch up sometimes',
      isRead: true,
      isReceived: false,
      isFavorite: false,
      isSent: true,
      isDraft: false,
      isTrash: false,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'dani@walla.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
    {
      id: 'e130',
      subject: 'Thank you!',
      body: `We aren’t going out for dinner this evening.`,
      isRead: false,
      isReceived: true,
      isFavorite: false,
      isSent: false,
      isDraft: false,
      isTrash: true,
      sentAt: getRandomTime('2024-03-01', '2024-06-05'),
      removedAt: null,
      from: 'dorhakim100@gmail.com',
      to: 'user@appsus.com',
      profilePic: `Profiles-SVG/${utilService.getRandomIntInclusive(1, 8)}.svg`,
      backgroundColor: utilService.getRandomColor(),
    },
  ]

  storageService._save(MAIL_KEY, mails)

  return mails
}

function getDefaultFilter(filterBy = { txt: '', readStatus: 'All' }) {
  // console.log(filterBy)
  return { txt: '', readStatus: 'All' }
}

function saveToStorage(key, val) {
  localStorage.setItem(key, JSON.stringify(val))
}

function loadFromStorage(key) {
  var val = localStorage.getItem(key)
  return JSON.parse(val)
}

function save(mail) {
  if (mail.id) {
    return storageService.put(MAIL_KEY, mail)
  } else {
    return storageService.post(MAIL_KEY, mail)
  }
}

function get(mailId) {
  return storageService.get(MAIL_KEY, mailId).then((mail) => {
    // mail = _setNextPrevMailId(mail)
    return mail
  })
}

function getComposeFromSearchParams(searchParams) {
  return {
    to: +searchParams.get('to') || '',
    subject: searchParams.get('subject') || '',
    body: searchParams.get('body') || '',
  }
}

function getRandomTime(start, end) {
  const startDate = new Date(start).getTime()
  const endDate = new Date(end).getTime()

  const randomTimestamp =
    Math.floor(Math.random() * (endDate - startDate + 1)) + startDate

  return new Date(randomTimestamp)
}
